Repository ITurres/catalog_of_things, pull requests merged in 2023-11, with the labels that each got.

#24 Issue #3 🎫: Genre class
  helpers/generate_id.rb
  lib/genre.rb
Labels: enhancement

#28 Issues 🎟️ #5 and #6 : Label and Book Classes
  lib/book.rb
  lib/label.rb
Labels: enhancement

#29 Issue #16 🎫: Game class Data Preservation && Schema
  .gitattributes
  db/data/games.json
  db/schema.sql
  lib/game.rb
  modules/json_data_manager.rb
Labels: enhancement, db

#32 Issue #14 🎫: Game class Unit Tests
  lib/game.rb
  lib/item.rb
  spec/lib_spec/game_spec.rb
Labels: tests

#33 Issue #10 🎫: MusicAlbum and Genre - db schema
  db/data/music_albums.json
  db/schema.sql
  lib/music_album.rb
Labels: enhancement, db

#37 Issue #1 🎫: MusicAlbum and Genre UI
  lib/app.rb
  modules/json_data_manager.rb
Labels: UI

#38 Tests 🎫 #18 ✅ For Author
  spec/lib_spec/author_spec.rb
Labels: tests

#40 Issue #2 🎫: MusicAlbum and Genre class - Unit Tests
  lib/music_album.rb
  spec/lib_spec/genre_spec.rb
  spec/lib_spec/music_album_spec.rb
Labels: enhancement, tests

#43 Catalog Manager App - Final PR 🎫
  .gitattributes
  .github/workflows/linters.yml
  .github/workflows/tests.yml
  .rspec
  .rubocop.yml
  Gemfile
  Gemfile.lock
  LICENSE
  README.md
  assets/catalog-manager-logo.png
  assets/uml diagram.png
  db/data/books.json
  db/data/games.json
  db/data/music_albums.json
  db/schema.sql
  helpers/generate_id.rb
  helpers/get_basic_inputs.rb
  lib/app.rb
  lib/author.rb
  lib/book.rb
  lib/game.rb
  lib/genre.rb
  lib/item.rb
  lib/label.rb
  lib/music_album.rb
  main.rb
  modules/json_data_manager.rb
  spec/lib_spec/author_spec.rb
  spec/lib_spec/book_spec.rb
  spec/lib_spec/game_spec.rb
  spec/lib_spec/genre_spec.rb
  spec/lib_spec/item_rspec.rb
  spec/lib_spec/label_spec.rb
  spec/lib_spec/music_album_spec.rb
  spec/spec_helper.rb
Labels: documentation, enhancement, tests, UI, db, setup
